CREATE DATABASE IF NOT EXISTS FIAP_FISHING;
USE FIAP_FISHING;

CREATE TABLE IF NOT EXISTS TB_USUARIO (
    ID_US INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN_US VARCHAR(100) NOT NULL,
    SENHA_US VARCHAR(100) NOT NULL
);
